[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = espidf
monitor_speed = 115200
upload_speed = 921600

build_flags =
  -DAPP_PLATFORM_ESP32=1
  -DBOARD_ESP32_NODEMCU_V1=1
  -DAPP_ENABLE_BRINGUP_TESTS=1