#ifndef CONFIG_UI_H
#define CONFIG_UI_H

#define APP_DISPLAY_MASTER_CONTRAST 8u

#define APP_UI_RC_PAGE_AXIS_CHANNEL      1u
#define APP_UI_RC_VERTICAL_AXIS_CHANNEL  2u
#define APP_UI_RC_INTERACT_CHANNEL       6u
#define APP_UI_RC_ENTER_CHANNEL          7u
#define APP_UI_RC_INPUT_ENABLE_CHANNEL  10u

#define APP_UI_RC_AXIS_LOW_THRESHOLD      600u
#define APP_UI_RC_AXIS_NEUTRAL_LOW        850u
#define APP_UI_RC_AXIS_NEUTRAL_HIGH      1134u
#define APP_UI_RC_AXIS_HIGH_THRESHOLD    1384u

#define APP_UI_RC_ACTION_OFF_THRESHOLD    600u
#define APP_UI_RC_ACTION_ON_THRESHOLD    1384u
#define APP_UI_RC_ENABLE_OFF_THRESHOLD   1200u
#define APP_UI_RC_ENABLE_ON_THRESHOLD    1384u

#define APP_UI_RC_PAGE_RIGHT_HIGH         1
#define APP_UI_RC_VERTICAL_UP_HIGH        1
#define APP_UI_RC_INTERACT_ACTIVE_HIGH    1
#define APP_UI_RC_ENTER_ACTIVE_HIGH       1
#define APP_UI_RC_INPUT_ENABLE_ACTIVE_HIGH 1

#define APP_UI_TASK_PERIOD_MS       50u
#define APP_UI_RENDER_PERIOD_MS    200u
#define APP_UI_RETRY_MS            1000u

#endif
